language: node_js
node_js:
  - "4.0"
addons:
  firefox: "42.0"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"